export const SEQUELIZE = 'SEQUELIZE';
export const DEVELOPMENT = 'development';
export const TEST = 'test';
export const PRODUCTION = 'production';

export const POSITION_REPOSITORY = 'POSITION_REPOSITORY';
export const PERSON_REPOSITORY = 'PERSON_REPOSITORY';
export const EMPLOYEE_REPOSITORY = 'EMPLOYEE_REPOSITORY';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const ROLE_REPOSITORY = 'ROLE_REPOSITORY';
export const USER_ROLE_REPOSITORY = 'USER_ROLE_REPOSITORY';

export const SUMMARY_1_REPOSITORY = 'SUMMARY_1_REPOSITORY';
export const SUMMARY_2_REPOSITORY = 'SUMMARY_2_REPOSITORY';
export const SUMMARY_3_REPOSITORY = 'SUMMARY_3_REPOSITORY';

export const BEARER_KEY = 'Bearer';
export const ROLES_KEY = 'ROLES';
